/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAhabanzaRouteImport } from './routes/_authenticated/ahabanza'
import { Route as AuthenticatedAmatekaRouteImport } from './routes/_authenticated/amateka'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIkizaminiRouteImport } from './routes/_authenticated/ikizamini'
import { Route as AuthenticatedKwiyigishaRouteImport } from './routes/_authenticated/kwiyigisha'
import { Route as AuthenticatedUmwirondoroRouteImport } from './routes/_authenticated/umwirondoro'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAhabanzaRoute = AuthenticatedAhabanzaRouteImport.update({
  id: '/ahabanza',
  path: '/ahabanza',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmatekaRoute = AuthenticatedAmatekaRouteImport.update({
  id: '/amateka',
  path: '/amateka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIkizaminiRoute = AuthenticatedIkizaminiRouteImport.update({
  id: '/ikizamini',
  path: '/ikizamini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKwiyigishaRoute = AuthenticatedKwiyigishaRouteImport.update({
  id: '/kwiyigisha',
  path: '/kwiyigisha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUmwirondoroRoute =
  AuthenticatedUmwirondoroRouteImport.update({
    id: '/umwirondoro',
    path: '/umwirondoro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ahabanza': typeof AuthenticatedAhabanzaRoute
  '/amateka': typeof AuthenticatedAmatekaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ikizamini': typeof AuthenticatedIkizaminiRoute
  '/kwiyigisha': typeof AuthenticatedKwiyigishaRoute
  '/umwirondoro': typeof AuthenticatedUmwirondoroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ahabanza': typeof AuthenticatedAhabanzaRoute
  '/amateka': typeof AuthenticatedAmatekaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ikizamini': typeof AuthenticatedIkizaminiRoute
  '/kwiyigisha': typeof AuthenticatedKwiyigishaRoute
  '/umwirondoro': typeof AuthenticatedUmwirondoroRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ahabanza': typeof AuthenticatedAhabanzaRoute
  '/_authenticated/amateka': typeof AuthenticatedAmatekaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ikizamini': typeof AuthenticatedIkizaminiRoute
  '/_authenticated/kwiyigisha': typeof AuthenticatedKwiyigishaRoute
  '/_authenticated/umwirondoro': typeof AuthenticatedUmwirondoroRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/admin'
    | '/ahabanza'
    | '/amateka'
    | '/dashboard'
    | '/ikizamini'
    | '/kwiyigisha'
    | '/umwirondoro'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/admin'
    | '/ahabanza'
    | '/amateka'
    | '/dashboard'
    | '/ikizamini'
    | '/kwiyigisha'
    | '/umwirondoro'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/ahabanza'
    | '/_authenticated/amateka'
    | '/_authenticated/dashboard'
    | '/_authenticated/ikizamini'
    | '/_authenticated/kwiyigisha'
    | '/_authenticated/umwirondoro'
    | '/admin/login'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ahabanza': {
      id: '/_authenticated/ahabanza'
      path: '/ahabanza'
      fullPath: '/ahabanza'
      preLoaderRoute: typeof AuthenticatedAhabanzaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amateka': {
      id: '/_authenticated/amateka'
      path: '/amateka'
      fullPath: '/amateka'
      preLoaderRoute: typeof AuthenticatedAmatekaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ikizamini': {
      id: '/_authenticated/ikizamini'
      path: '/ikizamini'
      fullPath: '/ikizamini'
      preLoaderRoute: typeof AuthenticatedIkizaminiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kwiyigisha': {
      id: '/_authenticated/kwiyigisha'
      path: '/kwiyigisha'
      fullPath: '/kwiyigisha'
      preLoaderRoute: typeof AuthenticatedKwiyigishaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/umwirondoro': {
      id: '/_authenticated/umwirondoro'
      path: '/umwirondoro'
      fullPath: '/umwirondoro'
      preLoaderRoute: typeof AuthenticatedUmwirondoroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAhabanzaRoute: typeof AuthenticatedAhabanzaRoute
  AuthenticatedAmatekaRoute: typeof AuthenticatedAmatekaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIkizaminiRoute: typeof AuthenticatedIkizaminiRoute
  AuthenticatedKwiyigishaRoute: typeof AuthenticatedKwiyigishaRoute
  AuthenticatedUmwirondoroRoute: typeof AuthenticatedUmwirondoroRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAhabanzaRoute: AuthenticatedAhabanzaRoute,
  AuthenticatedAmatekaRoute: AuthenticatedAmatekaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIkizaminiRoute: AuthenticatedIkizaminiRoute,
  AuthenticatedKwiyigishaRoute: AuthenticatedKwiyigishaRoute,
  AuthenticatedUmwirondoroRoute: AuthenticatedUmwirondoroRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
